// Mobile App Mock Data Constants

export const MOCK_STATS = {
  total_bookings: 128,
  pending_bookings: 12,
  total_services: 36,
  total_revenue: 42500,
  upcoming_bookings_count: 3,
};

export const MOCK_RECENT_BOOKINGS = [
  {
    id: "1",
    customerName: "Priya Sharma",
    serviceName: "Bridal Makeup Package",
    amount: 15000,
    status: "confirmed",
  },
  {
    id: "2",
    customerName: "Ananya Verma",
    serviceName: "Party Makeup",
    amount: 3500,
    status: "pending",
  },
  {
    id: "3",
    customerName: "Meera Patel",
    serviceName: "Pre-Wedding Shoot Makeup",
    amount: 8000,
    status: "confirmed",
  },
  {
    id: "4",
    customerName: "Sneha Reddy",
    serviceName: "Engagement Look",
    amount: 12000,
    status: "completed",
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "1",
    customerName: "Priya Sharma",
    serviceName: "Bridal Makeup Package",
    bookingDate: "Mar 5, 2026",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    status: "confirmed",
    totalAmount: 15000,
    createdAt: "Mar 3, 2026",
    avatarInitials: "PS",
  },
  {
    id: "2",
    customerName: "Ananya Verma",
    serviceName: "Party Makeup",
    bookingDate: "Mar 5, 2026",
    startTime: "4:00 PM",
    endTime: "5:30 PM",
    status: "pending",
    totalAmount: 3500,
    createdAt: "Mar 4, 2026",
    avatarInitials: "AV",
  },
  {
    id: "3",
    customerName: "Meera Patel",
    serviceName: "Pre-Wedding Shoot Makeup",
    bookingDate: "Mar 6, 2026",
    startTime: "6:00 AM",
    endTime: "8:00 AM",
    status: "confirmed",
    totalAmount: 8000,
    createdAt: "Mar 3, 2026",
    avatarInitials: "MP",
  },
  {
    id: "4",
    customerName: "Sneha Reddy",
    serviceName: "Engagement Look",
    bookingDate: "Mar 8, 2026",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    status: "confirmed",
    totalAmount: 12000,
    createdAt: "Mar 2, 2026",
    avatarInitials: "SR",
  },
  {
    id: "5",
    customerName: "Kavya Singh",
    serviceName: "Hair Styling",
    bookingDate: "Feb 28, 2026",
    startTime: "3:00 PM",
    endTime: "4:00 PM",
    status: "completed",
    totalAmount: 2500,
    createdAt: "Feb 25, 2026",
    avatarInitials: "KS",
  },
  {
    id: "6",
    customerName: "Ritu Agarwal",
    serviceName: "Natural Makeup",
    bookingDate: "Feb 27, 2026",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    status: "completed",
    totalAmount: 2000,
    createdAt: "Feb 24, 2026",
    avatarInitials: "RA",
  },
  {
    id: "7",
    customerName: "Deepika Nair",
    serviceName: "Mehendi Function Makeup",
    bookingDate: "Feb 25, 2026",
    startTime: "5:00 PM",
    endTime: "6:30 PM",
    status: "cancelled",
    totalAmount: 4500,
    createdAt: "Feb 22, 2026",
    avatarInitials: "DN",
  },
];

export const MOCK_SUMMARY = {
  upcoming_bookings_count: 3,
  pending_bookings: 2,
  completed_bookings: 2,
};

export const SERVICES = [
  {
    id: "1",
    name: "Bridal Makeup Package",
    description:
      "Complete bridal makeup with hairstyling, draping & jewellery setting",
    duration: "3 hrs",
    timesBooked: 89,
    price: "₹15,000",
    rating: 4.9,
    iconColor: "#ec4899",
    icon: "heart" as const,
  },
  {
    id: "2",
    name: "Facial & Skin Prep",
    description: "Pre-event skin prep facial with hydration and glow treatment",
    duration: "1.5 hrs",
    timesBooked: 73,
    price: "₹3,000",
    rating: 4.7,
    iconColor: "#22c55e",
    icon: "leaf" as const,
  },
  {
    id: "3",
    name: "Editorial / Fashion Makeup",
    description:
      "Creative, bold looks for photoshoots, portfolios & fashion shows",
    duration: "2.5 hrs",
    timesBooked: 21,
    price: "₹10,000",
    rating: 4.8,
    iconColor: "#a855f7",
    icon: "diamond" as const,
  },
  {
    id: "4",
    name: "Natural / No-Makeup Look",
    description: "Subtle enhancement for a 'my skin but better' natural glow",
    duration: "1 hr",
    timesBooked: 58,
    price: "₹2,000",
    rating: 4.5,
    iconColor: "#06b6d4",
    icon: "sparkles" as const,
  },
  {
    id: "5",
    name: "Party Makeup",
    description: "Glamorous looks for parties, events & celebrations",
    duration: "1.5 hrs",
    timesBooked: 102,
    price: "₹3,500",
    rating: 4.6,
    iconColor: "#f59e0b",
    icon: "star" as const,
  },
  {
    id: "6",
    name: "Engagement Look",
    description: "Elegant engagement day makeup with soft glam finish",
    duration: "2 hrs",
    timesBooked: 45,
    price: "₹8,000",
    rating: 4.8,
    iconColor: "#3b82f6",
    icon: "ribbon" as const,
  },
  {
    id: "7",
    name: "Hair Styling",
    description:
      "Professional hairstyling for all occasions - buns, curls & braids",
    duration: "1 hr",
    timesBooked: 67,
    price: "₹2,500",
    rating: 4.4,
    iconColor: "#14b8a6",
    icon: "cut" as const,
  },
  {
    id: "8",
    name: "Mehendi Function Look",
    description: "Vibrant, fun makeup look perfect for mehendi celebrations",
    duration: "1.5 hrs",
    timesBooked: 38,
    price: "₹4,500",
    rating: 4.7,
    iconColor: "#ef4444",
    icon: "flower" as const,
  },
  {
    id: "9",
    name: "Airbrush Makeup",
    description:
      "Flawless airbrush application for a long-lasting porcelain finish",
    duration: "2 hrs",
    timesBooked: 31,
    price: "₹12,000",
    rating: 4.9,
    iconColor: "#8b5cf6",
    icon: "color-palette" as const,
  },
  {
    id: "10",
    name: "Saree Draping",
    description:
      "Expert saree draping in multiple styles - Nivi, Bengali, Gujarati",
    duration: "30 min",
    timesBooked: 54,
    price: "₹1,500",
    rating: 4.3,
    iconColor: "#f97316",
    icon: "shirt" as const,
  },
];

export const MOCK_ARTIST = {
  name: "User",
  title: "Professional Makeup Artist",
  location: "Bangalore, India",
  bio: "Certified bridal & fashion makeup artist with 6+ years of experience. Specializing in HD airbrush, traditional & modern bridal looks.",
  completion: 85,
  email: "user@gmail.com",
  phone: "+91 98765 43210",
  bookings: 128,
  rating: 5,
  reviews: 96,
  experience: "6 yrs",
};

export const STATUS_FILTERS = [
  "All",
  "Pending",
  "Confirmed",
  "Completed",
  "Cancelled",
];

export const STATUS_COLORS: Record<
  string,
  { text: string; dot: string; bg: string }
> = {
  confirmed: { text: "#22c55e", dot: "#22c55e", bg: "rgba(34, 197, 94, 0.1)" },
  pending: { text: "#f59e0b", dot: "#f59e0b", bg: "rgba(245, 158, 11, 0.1)" },
  completed: { text: "#06b6d4", dot: "#06b6d4", bg: "rgba(6, 182, 212, 0.1)" },
  cancelled: { text: "#ef4444", dot: "#ef4444", bg: "rgba(239, 68, 68, 0.1)" },
};
